apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gpte-catalog-registry-policy
  namespace: acm-policies
  annotations:
    policy.open-cluster-management.io/standards: 
    policy.open-cluster-management.io/categories: 
    policy.open-cluster-management.io/controls: 
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: gpte-catalog-registry-policy
      spec:
        remediationAction: inform # will be overridden by remediationAction in parent policy
        severity: low
        namespaceSelector:
          exclude: ["kube-*"]
          include: ["default"]
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: CatalogSource
              metadata:
                name: redhat-gpte-nexus
                namespace: openshift-marketplace
              spec:
                displayName: Red Hat GPTE (Nexus)
                image: quay.io/gpte-devops-automation/nexus-catalog:v1.0.1
                sourceType: grpc
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-object-based-policy
  namespace: acm-policies
placementRef:
  name: placement-object-based-policy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: object-based-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-object-based-policy
  namespace: acm-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["cluster-gm"]}
