apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: gpte-exc-op-policy
  namespace: acm-policies
  annotations:
    policy.open-cluster-management.io/standards: null
    policy.open-cluster-management.io/categories: null
    policy.open-cluster-management.io/controls: null
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: openshift-exc-subs-policy
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: mustnothave
            objectDefinition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                name: openshift-pipelines-operator-rh
                namespace: openshift-operators
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: openshift-exc-csv-policy
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: mustnothave
            objectDefinition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: ClusterServiceVersion
              metadata:
                name: redhat-openshift-pipelines.v1.4.1
                namespace: openshift-operators
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-gpte-exc-op-policy
  namespace: acm-policies
placementRef:
  name: placement-gpte-exc-op-policy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: gpte-exc-op-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-gpte-exc-op-policy
  namespace: acm-policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: dev
        operator: In
        values:
          - 'true'
