apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: my-policy
  namespace: acm-policies
  annotations:
    policy.open-cluster-management.io/standards: 
    policy.open-cluster-management.io/categories: 
    policy.open-cluster-management.io/controls: 
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: openshift-pipelines-pol
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                name: openshift-pipelines-operator-rh
                namespace: openshift-operators
              spec:
                channel: stable
                installPlanApproval: Automatic
                name: openshift-pipelines-operator-rh
                source: redhat-operators
                sourceNamespace: openshift-marketplace
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: openshift-gitops-pol
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                name: openshift-gitops-operator
                namespace: openshift-operators
              spec:
                channel: preview
                installPlanApproval: Automatic
                name: openshift-gitops-operator
                source: redhat-operators
                sourceNamespace: openshift-marketplace

  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: openshift-serverless-pol
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                name: serverless-operator
                namespace: openshift-operators
              spec:
                channel: stable
                installPlanApproval: Automatic
                name: serverless-operator
                source: redhat-operators
                sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-my-policy
  namespace: acm-policies
placementRef:
  name: placement-my-policy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: my-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-my-policy
  namespace: acm-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: name, operator: In, values: ["cluster-gm"]}
